before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development
language: ruby
rvm:
  # Alti only supports Ruby >= 2.3
  - 2.3.5
  - 2.4.2
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
