before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development
language: ruby
rvm:
  # Test 2.3.0 itself since that's our min version
  - 2.3.0
  # Then test the latest patches for each minor after that
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
